#pragma config(StandardModel, "RVW Buggybot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void doLeftTurn() {
	int initialHeading = SensorValue[gyro];
	int targetHeading = initialHeading -900;
	// 0, -900, -1800, -2700, -3600
  motor[leftMotor] = -50;
	motor[rightMotor] = 50;
	while (SensorValue[gyro] > targetHeading + 100) {
	}
	motor[leftMotor] = -10;
	motor[rightMotor] = 10;
	while (SensorValue[gyro] > targetHeading) {}
	stopAllMotors();
}

void doRightTurn() {
	int initialHeading = SensorValue[gyro];
	int targetHeading = initialHeading + 900;
  motor[leftMotor] = 50;
	motor[rightMotor] = -50;
	while (SensorValue[gyro] < targetHeading - 100) {
	}
	motor[leftMotor] = 10;
	motor[rightMotor] = -10;
	while (SensorValue[gyro] < targetHeading) {}
	stopAllMotors();
}

bool canMove() {
	return SensorValue[sonar] > 10;
}

void moveUntilLine() {
	int minLightValue = 100;
	int maxLightValue = 0;
	motor[leftMotor] = 50;
	motor[rightMotor] = 50;
	while(SensorValue[light] > 70 && canMove()) {
		if (SensorValue[light] < minLightValue) {
			minLightValue = SensorValue[light];
	  }
	  if (SensorValue[light] > maxLightValue) {
	  	maxLightValue = SensorValue[light];
	  }
	}
	if (SensorValue[light] < minLightValue) {
		minLightValue = SensorValue[light];
	}
	if (SensorValue[light] > maxLightValue) {
	 	maxLightValue = SensorValue[light];
	}
	wait(0.5);
	stopAllMotors();
	writeDebugStreamLine("Minimum light value seen: %d, max light value seen: %d", minLightValue, maxLightValue);
	writeDebugStreamLine("Broke out of moveUntilLine; light is %d, sonar is %d", SensorValue[light], SensorValue[sonar]);
	if (canMove()) {
	  forward(0.5, seconds, 30);
  }
}

task main()
{
	doRightTurn();
	forward(2, seconds, 40);

	while(true) {
		if (!canMove()) {
			doRightTurn();
		} else {
			moveUntilLine();
			doLeftTurn();
	  }
	}
}


//	turnRight(.35);

//  while(SensorValue[light] < 100)
//  {
//  	forward(1, seconds, 15);
//	}

//	turnRight(.35);
//  while(SensorValue[sonar] > 20)
//  {
//  	forward(1, seconds, 15);
//	}
//}
